services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-earthquakes}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-earthquakes}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-migrate:
    build: .
    working_dir: /app
    command: alembic -c db/alembic.ini upgrade head
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-earthquakes}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-earthquakes}
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db-migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:


